#! /bin/sh

# start sxhkd
sxhkd -c /home/hannes/.config/sxhkd/sxhkdrc &

# ------------------------------------

# configure bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config active_border_color  '#FFFFFF'
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Nextcloud state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# ------------------------------------

# Apps 

# shutdown previous instances
killall -q xfce4-clipman
killall -q dunst
killall -q redshift-gtk

# fix cursor
xsetroot -cursor_name left_ptr &

# set keyboard map
setxkbmap -layout de &

# polybar
~/.config/polybar/launch.sh --material &

# set lower boundary for light
light -N 1.3 &

# start picom
picom -CGb --vsync --backend glx &

# start auth polkit agent
lxpolkit &

# restore wallpaper
nitrogen --restore &

# autostart tools
xfce4-clipman &
dunst &
nm-applet &
redshift-gtk -l 52.28:8.92 &
/home/hannes/Applications/Nextcloud-3.4.4-x86_64.AppImage &


#######################
# create xcape bindings
#######################

# ctrl = escape for vim (bad for games xD)
# xcape -e 'Control_L=Escape'

# map super to show rofi
xcape -e 'Super_L=Alt_L|F12'
