#! /bin/sh

# start sxhkd
sxhkd -c /home/hannes/.config/sxhkd/sxhkdrc &

# ------------------------------------

# configure bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config active_border_color  '#FFFFFF'
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Nextcloud state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# ------------------------------------

# Apps 
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh --docky &
nm-applet &
light -N 1.3 &
picom -CGb --vsync --backend glx &
nitrogen --restore &
setxkbmap -layout de &
xfce4-clipman &
dunst &
redshift-gtk -l 52.28:8.92 &
